version: '3.8'

services:
  app:
    container_name: docker-app
    build: .
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - app-network
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - APP_PORT=5000
      - DB_HOST=postgres
      - REDIS_HOST=redis

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - app-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
networks:
  app-network:
    driver: bridge